# Generated by Django 4.2.1 on 2023-12-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_storagerequests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='best_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='task.neuralnetwork'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_mark',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
